using System;

namespace Luxbook.MVC.Models
{
    /// <summary>
    ///     Represents a single rule that an alert can be generated by
    /// </summary>
    public class Rule
    {
        public enum ComparisonOperator
        {
            GreaterThan,
            Equal,
            LessThan
        }

        /// <summary>
        ///     This enum determines if the comparison is done against a fixed value e.g. if a is greater than 6 or against a
        ///     property
        ///     e.g. if a is greater than b
        /// </summary>
        public enum ComparisonType
        {
            FixedValue,
            CompareAgainstTargetProperty
        }

        public enum EventTargetProperty
        {
            Luxbet_WinPercentage,
            Tab_WinPercentage,
            Runner_Count
        }

        public enum RuleCategory
        {
            Price,
            Place,
            WinPercentage,
            Scratchings
        }

        public enum RuleType
        {
            Event,
            Runner
        }

        public enum RunnerTargetProperty
        {
            Fx_Bob = 0,
            Lxb_Fw = 1,
            Vic_Fw = 2,
            Qld_Fw = 7,
            Pm_Dvp = 3,
            BFR_FW_L1 = 4,
            BFR_WAP = 5,
            SDP = 6,
        }

        public int Rule_Id { get; set; }
        public string Name { get; set; }

        public string Property_Name { get; set; }
        public ComparisonOperator Comparison_Operator { get; set; }

        /// <summary>
        ///     This is used if ComparisonType is FixedValue
        /// </summary>
        public decimal? Target_Value { get; set; }

        public string Meeting_Type { get; set; }

        public ComparisonType Comparison_Type { get; set; }

        /// <summary>
        ///     This is used if the ComparisonType is CompareAgainstTargetProperty
        /// </summary>
        public string Target_Property { get; set; }

        public RuleType Type { get; set; }

        public RuleCategory Category { get; set; }

        public bool Enabled { get; set; }

        public DateTime Date_Created { get; set; }

        /// <summary>
        ///     Username that created this rule
        /// </summary>
        public string LID { get; set; }
    }
}