<%@ Import Namespace = "System.Configuration"  %>
<%@ Import Namespace = "System.Globalization"  %>
<%@ Import Namespace = "System.IO"             %>
<%@ Import Namespace = "System.XML"            %>
<%@ Import Namespace = "System.Net"            %>
<%@ Import Namespace = "System.Net.Mail"       %>
<%@ Import Namespace = "System.Data.SQLClient" %>
<%@ Import Namespace = "System.Data"           %>
<%@ Import Namespace = "System.Threading"      %>
<script language=VBScript runat=server>

Dim APDS_API As String = ConfigurationManager.AppSettings("APDS_API")

</script>